// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAcPiGj9JmPZT3cGbA5bqM1TPb_hG1n55E",
      authDomain: "tonewood-ea5c7.firebaseapp.com",
      projectId: "tonewood-ea5c7",
      storageBucket: "tonewood-ea5c7.appspot.com",
      messagingSenderId: "160218984374",
      appId: "1:160218984374:web:63e2221ef010f034a69b17",
      measurementId: "G-ETC2CVT1CS"
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyAcPiGj9JmPZT3cGbA5bqM1TPb_hG1n55E",
      authDomain: "tonewood-ea5c7.firebaseapp.com",
      projectId: "tonewood-ea5c7",
      storageBucket: "tonewood-ea5c7.appspot.com",
      messagingSenderId: "160218984374",
      appId: "1:160218984374:web:63e2221ef010f034a69b17",
      measurementId: "G-ETC2CVT1CS"
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: "AIzaSyAcPiGj9JmPZT3cGbA5bqM1TPb_hG1n55E",
      authDomain: "tonewood-ea5c7.firebaseapp.com",
      projectId: "tonewood-ea5c7",
      storageBucket: "tonewood-ea5c7.appspot.com",
      messagingSenderId: "160218984374",
      appId: "1:160218984374:web:63e2221ef010f034a69b17",
      measurementId: "G-ETC2CVT1CS"
  );

  static const FirebaseOptions macos = FirebaseOptions(
      apiKey: "AIzaSyAcPiGj9JmPZT3cGbA5bqM1TPb_hG1n55E",
      authDomain: "tonewood-ea5c7.firebaseapp.com",
      projectId: "tonewood-ea5c7",
      storageBucket: "tonewood-ea5c7.appspot.com",
      messagingSenderId: "160218984374",
      appId: "1:160218984374:web:63e2221ef010f034a69b17",
      measurementId: "G-ETC2CVT1CS"
  );

  static const FirebaseOptions windows = FirebaseOptions(
      apiKey: "AIzaSyAcPiGj9JmPZT3cGbA5bqM1TPb_hG1n55E",
      authDomain: "tonewood-ea5c7.firebaseapp.com",
      projectId: "tonewood-ea5c7",
      storageBucket: "tonewood-ea5c7.appspot.com",
      messagingSenderId: "160218984374",
      appId: "1:160218984374:web:63e2221ef010f034a69b17",
      measurementId: "G-ETC2CVT1CS"
  );
}
